-- الإعداد الكامل لموقع معدات السعودية
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;
drop policy if exists public_insert_messages on public.messages;
create policy public_insert_messages on public.messages
for insert to anon, authenticated
with check (char_length(trim(message)) between 1 and 2000);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  author_name text not null default 'زائر',
  comment text not null,
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;
drop policy if exists public_read_comments on public.comments;
create policy public_read_comments on public.comments
for select to anon, authenticated
using (true);

drop policy if exists public_insert_comments on public.comments;
create policy public_insert_comments on public.comments
for insert to anon, authenticated
with check (
  char_length(trim(author_name)) between 1 and 50
  and char_length(trim(comment)) between 1 and 1000
);
