-- إعداد الرسائل الخاصة لموقع معدات السعودية
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists public_insert_messages on public.messages;
create policy public_insert_messages
on public.messages
for insert
to anon, authenticated
with check (true);

-- متعمد: لا توجد سياسة SELECT عامة.
-- النتيجة: زوار الموقع يستطيعون إرسال الرسائل ولا يستطيعون قراءتها.
